Restructure Data Structures content
hazelcast/management-center-docs pull request #120
Opened 2021-11-08 07:29 UTC by Serdaro

2021-12-07 18:09 UTC, JakeSCahill requested changes
Looks good.  A couple of suggestions.

2021-12-07 18:09 UTC, JakeSCahill commented on docs/modules/data-structures/pages/lock.adoc
> +To find the number of active locks in your cluster, use the following script:
Can we add headings to these? For example: 'Finding Active Locks'

2021-12-07 18:09 UTC, JakeSCahill commented on docs/modules/data-structures/pages/lock.adoc
> +[source,plain]
```suggestion
[source,javascript]
```

2021-12-07 18:09 UTC, JakeSCahill commented on docs/modules/data-structures/pages/lock.adoc
> +[source,plain]
```suggestion
[source,javascript]
```

2021-12-07 18:09 UTC, JakeSCahill commented on docs/modules/data-structures/pages/lock.adoc
> +[source,plain]
```suggestion
[source,javascript]
```

2021-12-07 18:09 UTC, JakeSCahill commented on docs/modules/data-structures/pages/lock.adoc
> +[source,plain]
```suggestion
[source,javascript]
```

2021-12-07 18:09 UTC, JakeSCahill commented on docs/modules/data-structures/pages/lock.adoc
> +You can use the below scripts to retrieve various information
```suggestion
You can use these JavaScript functions to retrieve various information
```

2021-12-07 18:09 UTC, JakeSCahill commented on docs/modules/data-structures/pages/overview.adoc
> +
```suggestion
:page-aliases: monitor-imdg:monitor-dds.adoc
```

Redirects the old data structure page to this one.

2021-12-14 11:57 UTC, Serdaro commented on docs/modules/data-structures/pages/lock.adoc
> +To find the number of active locks in your cluster, use the following script:
added

2021-12-15 10:30 UTC, merged