CPO-46 Restructure Getting Started content
hazelcast/management-center-docs pull request #127
Opened 2021-12-03 09:16 UTC by Serdaro

2021-12-07 18:03 UTC, JakeSCahill requested changes
A great addition to the MC docs 😄  

It looks like a lot of suggestions, but lots of them are minor. For the bigger ones, please reach out if anything is unclear.

2021-12-07 18:03 UTC, JakeSCahill commented on docs/modules/get-started/pages/start-opensource.adoc
> +To complete this tutorial, you need the following:
One of the prerequisites for both tutorials should be to review the requirements in the overview.

2021-12-07 18:03 UTC, JakeSCahill commented on docs/modules/get-started/partials/nav.adoc
> +*** xref:user-interface.adoc[Menu and Toolbar]
Because this is such a big change, I think we can move these docs into the `get-started` directory. Just make sure to update links and add a `page-aliases` field to the new page so that Antora creates redirects.

2021-12-10 12:43 UTC, Serdaro commented on docs/modules/get-started/pages/start-enterprise.adoc
> +Note the `HZ_JET_ENABLED=true` variable; this enables the Jet engine since you are going to use SQL to create a map.
I needed to make it true, since it didn't work (SQL).

2021-12-10 12:44 UTC, Serdaro commented on docs/modules/get-started/pages/start-enterprise.adoc
> +In this step, we are going to start a local Management Center service with TLS enabled.
You meant "you" I guess, and sure :)

2021-12-10 12:47 UTC, Serdaro commented on docs/modules/get-started/pages/install.adoc
> +If you choose to install Management Center using binary packages, you need to start the
Yes, as we were talking about it with Emre, it is the step to make localhost:8080 is launchable.

2021-12-10 12:50 UTC, JakeSCahill commented on docs/modules/get-started/pages/start-enterprise.adoc
> +Note the `HZ_JET_ENABLED=true` variable; this enables the Jet engine since you are going to use SQL to create a map.
@frant-hartm is this expected?

2021-12-10 12:54 UTC, JakeSCahill commented on docs/modules/get-started/pages/install.adoc
> +If you choose to install Management Center using binary packages, you need to start the
Then maybe we should rename this page to installing and starting MC?

And include a snippet for how to start MC with Docker?

2021-12-10 15:13 UTC, JakeSCahill commented on docs/modules/get-started/pages/install.adoc
> +For example, you can learn about topics including how to start with a
It was mainly because the page is just a list now. But I suppose we can keep the examples 😄

2021-12-10 15:16 UTC, JakeSCahill commented on docs/modules/get-started/pages/start-enterprise.adoc
> +This tutorial allows you to start a licensed Management Center using Docker. It covers the following steps:
We can say, 'You'll complete the following steps'?

Starting a sentence with 'it' is bad practice. It's not always clear what 'it' refers to. Although it's clear that 'it' refers to the tutorial here, we should avoid it.

2021-12-13 14:58 UTC, frant-hartm commented on docs/modules/get-started/pages/start-enterprise.adoc
> +Note the `HZ_JET_ENABLED=true` variable; this enables the Jet engine since you are going to use SQL to create a map.
The following works:

```
docker run --network hazelcast-network \
  -e HZ_LICENSEKEY=$HZ_LICENSEKEY \
  -e HZ_CLUSTERNAME=hello-world \
  -p 5701:5701 \
  hazelcast/hazelcast-enterprise:5.0
```
I can see both the following log that jet is enabled:
```
2021-12-13 14:55:01,252 [ INFO] [main] [c.h.i.i.JetExtension]: [192.168.64.2]:5701 [hello-world] [5.0] Jet is enabled
```
and trying to run SQL query works as well:
```
$ docker run -it --network hazelcast-network hazelcast/hazelcast:5.0 hz-cli sql -t hello-world@192.168.64.2
Connected to Hazelcast 5.0 at [192.168.64.2]:5701 (+0 more)
Type 'help' for instructions
sql> select 1;
+------+
|EXPR$0|
+------+
|     1|
+------+
1 row(s) selected
```

The `HZ_JET_ENABLED` should not be required for zip distro or docker images.

2021-12-13 17:04 UTC, JakeSCahill approved these changes
LGTM

2021-12-13 17:07 UTC, merged