Fix: use xref for IMDG links
hazelcast/management-center-docs pull request #14
Opened 2021-02-10 11:52 UTC by danad02

Hi, I'm from MC team, a front-end developer.

While fixing broken IMDG docs links we discovered that some links in the docs are also broken (e.g. pointing to wrong sections).
This PR changes the remaining "raw" links to use cross-reference instead. 

Is there anything else that needs to be done?

2021-02-10 16:52 UTC, JakeSCahill requested changes
Some links are broken causing the build to fail.

2021-02-10 16:52 UTC, JakeSCahill commented on docs/modules/monitor-imdg/pages/dashboard.adoc
> +property explained in the xref:imdg:system-properties.adoc[System Properties appendix] of
This should be `xref:imdg:ROOT:system-properties.adoc[System Properties appendix]` because the content is in the ROOT module

2021-02-10 16:52 UTC, JakeSCahill commented on docs/modules/monitor-imdg/pages/monitor-dds.adoc
> +to the xref:idmg:jcache:setup.adoc#jcache-declarative-configuration[JCache Declarative Configuration]
Typo: `idmg` should be `imdg`

2021-02-10 16:52 UTC, JakeSCahill commented on docs/modules/monitor-imdg/pages/monitor-wan-replication.adoc
> +See the xref:imdg:wan.adoc[WAN Replication section]
Should be `xref:imdg:wan:wan.adoc[WAN Replication section]`

2021-02-10 16:52 UTC, JakeSCahill commented on docs/modules/ROOT/pages/getting-started.adoc
> +Also see xref:imdg:starting-members-clients.adoc[here] and link:https://jet-start.sh/docs/get-started/installation[here^] for information on starting the IMDG and Jet clusters, respectively.
Should be `xref:imdg:ROOT:starting-members-clients.adoc[here]`

2021-02-11 08:56 UTC, JakeSCahill requested changes

2021-02-11 08:56 UTC, JakeSCahill commented on docs/modules/ROOT/pages/getting-started.adoc
> +Also see xref:imdg:starting-members-clients.adoc[here] and link:https://jet-start.sh/docs/get-started/installation[here^] for information on starting the IMDG and Jet clusters, respectively.
```suggestion
Also see xref:imdg:ROOT:starting-members-clients.adoc[here] and link:{jet-docs}docs/get-started/installation[here^] for information on starting the IMDG and Jet clusters, respectively.
```

2021-02-11 08:56 UTC, JakeSCahill commented on docs/modules/monitor-imdg/pages/dashboard.adoc
> +property explained in the xref:imdg:system-properties.adoc[System Properties appendix] of
```suggestion
property explained in the xref:imdg:ROOT:system-properties.adoc[System Properties appendix] of
```

2021-02-11 08:56 UTC, JakeSCahill commented on docs/modules/monitor-imdg/pages/monitor-dds.adoc
> +to the xref:idmg:jcache:setup.adoc#jcache-declarative-configuration[JCache Declarative Configuration]
```suggestion
to the xref:imdg:jcache:setup.adoc#jcache-declarative-configuration[JCache Declarative Configuration]
```

2021-02-11 08:56 UTC, JakeSCahill commented on docs/modules/monitor-imdg/pages/monitor-wan-replication.adoc
> +See the xref:imdg:wan.adoc[WAN Replication section]
```suggestion
See the xref:imdg:wan:wan.adoc[WAN Replication section]
```

2021-02-11 09:54 UTC, JakeSCahill commented on docs/modules/monitor-imdg/pages/dashboard.adoc
> +property explained in the xref:imdg:system-properties.adoc[System Properties appendix] of
It's in the ROOT module, so we must specify that.

We could also do `xref:imdg::system-properties.adoc[]` with double colons `::`, but ROOT is more explicit

2021-02-11 10:58 UTC, merged

2021-02-11 11:01 UTC, danad02 commented
@JakeSCahill Thanks for taking care of those problems!