Update docs for MC-1225
hazelcast/management-center-docs pull request #142
Opened 2022-01-21 13:29 UTC by aberatcan

- Updated documentation for [https://hazelcast.atlassian.net/jira/software/projects/MC/boards/46?selectedIssue=MC-1225](https://hazelcast.atlassian.net/jira/software/projects/MC/boards/46?selectedIssue=MC-1225)

2022-01-24 19:25 UTC, promanenko commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +Set the xref:system-properties.adoc#hazelcast-mc-metrics-persistence-enabled[`hazelcast.mc.metrics.persistence.enabled`] property to `false`.
please add more details like: 
- it allows MC to run on OS that aren't supported by RocksDB;
- metrics are stored only in memory with this property;

2022-01-25 10:33 UTC, JakeSCahill requested changes
We say that RocksDB is a requirement in the product overview, which restricts the versions of certain OS you can use.

We should reword that paragraph and link to this section for users who don't have an OS version that supports RocksDB: https://github.com/hazelcast/management-center-docs/blob/main/docs/modules/getting-started/pages/overview.adoc#requirements

2022-01-25 10:33 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +Disabling Metrics Persistence allows MC to run on OS that aren't supported by RocksDB. Metrics are stored only in memory.
```suggestion
If you don't want metrics to be persisted on disk, set the xref:system-properties.adoc#hazelcast-mc-metrics-persistence-enabled[`hazelcast.mc.metrics.persistence.enabled`] property to `false`, which stores metrics only in memory.

TIP: Disabling persistence allows Management Center to run on an operating system that doesn't support RocksDB.
```

Can we move this above the 'Troubleshooting' section?

2022-01-25 10:33 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +To disable metrics persistence:
```suggestion
```

2022-01-25 10:33 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +Set the xref:system-properties.adoc#hazelcast-mc-metrics-persistence-enabled[`hazelcast.mc.metrics.persistence.enabled`] property to `false`.
```suggestion
```

2022-01-27 11:19 UTC, JakeSCahill commented on docs/modules/getting-started/pages/overview.adoc
>  You need Java Runtime Environment 1.8 or later to run Hazelcast Management Center.
I think here we need to call out the fact that although you 

Something like:

Management Center uses the RocksDB library to store metrics data on disk. Because of this dependency on RocksDB, Mac and Windows users must do one of the following:

- Use the official Management Center docker image.
- xref:deploy-manage:historical-metrics.adoc#disabling-metrics-persistence[Disable metric peristence].
- Meet the following requirements:
** Mac: Use at least version 10.15 version of Catalina.
** Windows: Install the Microsoft Visual C++ 2015 redistributable.

2022-01-27 11:21 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +TIP: Disabling persistence allows Management Center to run on an operating system that doesn't support RocksDB. See the xref:../../getting-started/pages/overview.adoc#os-requirements[Requirements sec
```suggestion
TIP: Disabling persistence allows Management Center to run on an operating system that doesn't support RocksDB. See the xref:getting-started:overview.adoc#os-requirements[Requirements section] for details.
```

2022-01-27 15:41 UTC, JakeSCahill commented on docs/modules/getting-started/pages/overview.adoc
>  Management Center uses RocksDB library to store metrics
```suggestion
Management Center uses the RocksDB library to store metrics
```

2022-01-27 15:41 UTC, JakeSCahill approved these changes
lgtm thanks 😄

2022-01-27 15:49 UTC, zhmaeff approved these changes

2022-01-27 15:53 UTC, merged