Update docs for MC-1285
hazelcast/management-center-docs pull request #144
Opened 2022-01-27 16:43 UTC by aberatcan

- updated docs for newly added env property

2022-01-27 17:55 UTC, JakeSCahill requested changes

2022-01-27 17:55 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/system-properties.adoc
> +|Operation timeout in milliseconds for scripts in MC. Default: 60000.
Could we be a bit more descriptive? I'm not sure what causes the timeout. Maybe a link to the scripting page would also help.

Is this the number of milliseconds that a script can be unable to connect to a cluster?

2022-01-27 18:21 UTC, promanenko commented on docs/modules/deploy-manage/pages/system-properties.adoc
> +|Operation timeout in milliseconds for scripts in MC. Default: 60000.
@aberatcan this timeout applies to all MC operations on the members, not only to scripts execution.
@JakeSCahill a bit of context https://hazelcast.slack.com/archives/C9S7BV74Z/p1642071001005500?thread_ts=1642070781.005000&cid=C9S7BV74Z

2022-01-28 15:51 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/system-properties.adoc
> +|Operation timeout in milliseconds for scripts in MC. Default: 60000.
Thanks @promanenko 😄 

In that case: 'Timeout in milliseconds for Management Center operations that wait for a response from members.'?

Also, this is a troubleshooting topic. Could we add an entry to this page? https://github.com/hazelcast/management-center-docs/blob/main/docs/modules/troubleshoot/pages/management-center.adoc

This is where we can discuss what to do if you experience a timeout when running scripts or SQL queries.

2022-02-17 09:46 UTC, JakeSCahill commented on docs/modules/troubleshoot/pages/management-center.adoc
> +new value to xref:deploy-manage:system-properties.adoc#hazelcast-mc-cluster-operation-timeout['hazelcast.mc.cluster.operation.timeout.millis'] property.
```suggestion
in the xref:deploy-manage:system-properties.adoc#hazelcast-mc-cluster-operation-timeout[`hazelcast.mc.cluster.operation.timeout.millis`] property.
```

2022-02-17 09:46 UTC, JakeSCahill commented on docs/modules/troubleshoot/pages/management-center.adoc
> +If you experience a timeout when running scripts or SQL queries, You can increase operation timeout value via setting
```suggestion
If you experience a timeout when running scripts or SQL queries, you can increase the timeout value 
```

2022-02-17 09:47 UTC, JakeSCahill requested changes
Just some minor sentence structure changes.

2022-02-17 09:59 UTC, JakeSCahill approved these changes

2022-02-17 10:41 UTC, merged