MC-1242 - configurable metrics thread pool size
hazelcast/management-center-docs pull request #145
Opened 2022-01-27 18:43 UTC by promanenko

2022-01-27 18:57 UTC, zhmaeff approved these changes

2022-01-28 10:20 UTC, JakeSCahill requested changes

2022-01-28 10:20 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/system-properties.adoc
> +|How many threads consume metrics from the cluster members. Default: `2`. See xref:historical-metrics.adoc[].
```suggestion
|Number of threads that are used to consume metrics from cluster members. Default: `2`. See xref:historical-metrics.adoc[].
```

2022-01-28 10:20 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +=== Metrics Consumption Delays
I think the title should reflect the problem rather than the reason. Users will search for their issue and won't necessarily know that it has anything to do with consumption delays.

Maybe something like 'Missing Values for Metrics'?

2022-01-28 10:20 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +If management Center is connected to a large cluster (30+ members) it may experience metric consumption delays resulting
```suggestion
Management Center may experience delays while consuming metrics from cluster members, resulting
```

2022-01-28 10:20 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +- Increase the amount of threads that consume metrics from the cluster members by setting xref:system-properties.adoc#hazelcast-mc-metrics-consumer-thread-pool-size[`hazelcast.mc.metrics.consumer.thr
```suggestion
```

2022-01-28 10:20 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +To resolve this issue, you can do the following:
```suggestion

To resolve this issue, increase the number of threads that consume metrics from the cluster members by setting the xref:system-properties.adoc#hazelcast-mc-metrics-consumer-thread-pool-size[`hazelcast.mc.metrics.consumer.thread.pool.size` property]
```

2022-01-28 10:20 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +in `N/A` or `0` displayed instead of the metric values.
```suggestion
in `N/A` or `0` displayed instead of the metric values. Delays usually occur when Management Center is connected to a large cluster of 30+ members.
```

2022-01-28 16:05 UTC, promanenko commented on docs/modules/deploy-manage/pages/historical-metrics.adoc
> +=== Metrics Consumption Delays
agree, changed to 'Missing Values for Metrics'

2022-01-28 16:56 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/system-properties.adoc
> +|[[hazelcast-mc-metrics-consumer-thread-pool-size]]hazelcast.mc.metrics.consumer.thread.pool.size
```suggestion
|[[hazelcast-mc-metrics-consumer-thread-pool-size]]`hazelcast.mc.metrics.consumer.thread.pool.size`
```

2022-01-28 16:57 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/system-properties.adoc
> +hz-mc start -Dhhazelcast.mc.metrics.consumer.thread.pool.size=5
```suggestion
hz-mc start -Dhazelcast.mc.metrics.consumer.thread.pool.size=5
```

2022-01-28 16:58 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/system-properties.adoc
> +hz-mc start -Dhhazelcast.mc.metrics.consumer.thread.pool.size=5
@promanenko just checking if this is a typo or intentional

2022-01-28 17:34 UTC, promanenko commented on docs/modules/deploy-manage/pages/system-properties.adoc
> +hz-mc start -Dhhazelcast.mc.metrics.consumer.thread.pool.size=5
a typo, thanks for catching that

2022-01-28 17:39 UTC, JakeSCahill approved these changes

2022-01-28 17:40 UTC, merged