Update SQL browser documentation
hazelcast/management-center-docs pull request #167
Opened 2022-03-14 13:50 UTC by zhmaeff

Related to MC-1370

2022-03-14 14:35 UTC, promanenko commented on docs/modules/tools/pages/sql-browser.adoc
> +you should see your mapping in the **Queryable objects** tree view:
could you please add an information about columns and indexes? 
And update the screenshot to contain columns of multiple types and indexes too?

2022-03-15 10:12 UTC, promanenko approved these changes

2022-03-15 12:14 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +It can be generated by cluster or inserted manually into the SQL editor.
```suggestion
You can type this statement into the editor, or you can generate it automatically.
```

2022-03-15 12:15 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +Click **Connect Maps** button
```suggestion
To generate the `CREATE MAPPING` statement automatically, click the *Connect Maps* button
```

2022-03-15 12:15 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +and select the map's name from the dropdown to generate `CREATE MAPPING` statement based on the map content:
```suggestion
and select an existing map from the dropdown:
```

2022-03-15 12:17 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +A generated `CREATE MAPPING` statement is inserted into the editor and can be adjusted to your needs.
```suggestion
If you need to change the generated statement, you can use the editor.
```

2022-03-15 12:19 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +NOTE: In some cases `CREATE MAPPING` statement can not be generated. The Possible reasons are: the map is empty, the map is stored in `NATIVE` format without indexes.
```suggestion
NOTE: You cannot generate a `CREATE MAPPING` statement for empty maps or maps that store entries in the `NATIVE` format without indexes.
```

2022-03-15 12:19 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +Click **Confirm & Run**.
```suggestion
Click *Confirm & Run*.
```

2022-03-15 12:19 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +After the successful `CREATE MAPPING` SQL statement execution,
```suggestion
After executing the `CREATE MAPPING` statement,
```

2022-03-15 12:20 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +you should see your mapping in the **Queryable objects** tree view:
```suggestion
you should see your mapping in the *Queryable objects* tree view:
```

2022-03-15 12:20 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +To execute a query, click **Execute Query**.
```suggestion
To execute a query, click *Execute Query*.
```

2022-03-15 12:20 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +After a successful query execution, you will see the results under **Query Results**
```suggestion
When the query is executed, the results are displayed under *Query Results*:
```

2022-03-15 12:22 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +This mode limits **Query Results** to the first 1000 records returned by the query.
```suggestion
```

2022-03-15 12:23 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +
```suggestion
```

2022-03-15 12:25 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +* **Stream last 1000 records**
```suggestion
* *Stream last 1000 records*: Display only the last 1000 records returned by the streaming query. The most recent record is always on the top of the list.
+
NOTE: This mode is only for displaying the results of streaming SQL queries.
```

2022-03-15 12:25 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +NOTE: Should be used for displaying the Streaming SQL query results.
```suggestion
```

2022-03-15 12:25 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +In this mode **Query Results** show only the last 1000 records returned by query,
```suggestion
```

2022-03-15 12:25 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +and the last record is always on the top of the list.
```suggestion
```

2022-03-15 12:26 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +You can use **Export** to export the query result as a **CSV** file in
```suggestion
You can use **Export** to export the query result as a CSV file in
```

2022-03-15 12:26 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +a format https://tools.ietf.org/html/rfc4180[RFC 4180] or as a **JSON** file.
```suggestion
the https://tools.ietf.org/html/rfc4180[RFC 4180 format] or as a JSON file.
```

2022-03-15 12:28 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +Each row contains **Execution Time**, **Execution Status** and **Query** values.
Can we describe what these fields are? What are the possible executions statuses for example?

We may want to put this information in a list or a table.

2022-03-15 12:28 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +You can also use **Clear Query Result** to remove the query results.
```suggestion
To remove the query results, click *Clear Query Result*.
```

Users skim for information, so we should lead with the information they are looking for.

2022-03-15 12:29 UTC, JakeSCahill requested changes
Minor suggestions and a request for more details.

2022-03-15 12:39 UTC, zhmaeff commented on docs/modules/tools/pages/sql-browser.adoc
> +Each row contains **Execution Time**, **Execution Status** and **Query** values.
I think the screenshot below shows all the possible values for statuses and other columns. WDYT?

2022-03-15 14:59 UTC, JakeSCahill approved these changes

2022-03-15 15:18 UTC, merged