5.1.4 - release notes
hazelcast/management-center-docs pull request #184
Opened 2022-07-04 15:01 UTC by promanenko

2022-07-04 15:17 UTC, zhmaeff commented on docs/modules/release-notes/partials/nav.adoc
> +** xref:release-notes:5-1-3.adoc[5.1.4]
```suggestion
** xref:release-notes:5-1-4.adoc[5.1.4]
```

2022-07-05 10:28 UTC, JakeSCahill requested changes
The enhancement sounds like it was a bug. We should clarify how this helps users.

I also added a few suggestions to focus the fix on how it benefits the user.

2022-07-05 10:28 UTC, JakeSCahill commented on docs/modules/release-notes/pages/5-1-4.adoc
> +* Jet metrics storage stores only Jet-related metrics. [MC-1532]
What was the previous behavior? How does this enhancement benefit the user?

2022-07-05 10:28 UTC, JakeSCahill commented on docs/modules/release-notes/pages/5-1-4.adoc
> +* Fixed the disabled "Upgrade Cluster" button after successfull rolling upgrade. [MC-1569]
```suggestion
* The *Upgrade Cluster* button is no longer disabled after you upgrade your members' codebase version during a rolling upgrade. [MC-1569]
```

2022-07-05 10:28 UTC, JakeSCahill commented on docs/modules/release-notes/pages/5-1-4.adoc
> +* Fixed an exception on `hz-mc start`. [MC-1403]
```suggestion
* The `hz-mc start`command no longer throws ClassNotFoundException. [MC-1403]
```

2022-07-05 10:28 UTC, JakeSCahill commented on docs/modules/release-notes/pages/5-1-4.adoc
> +* Fixed various Hazelcast Cloud integration issues. [MC-1591]
Can we be more specific? It looks like the work involved a lot of work to do with Pendo integration. How does this fix affect the user?

2022-07-05 10:55 UTC, promanenko commented on docs/modules/release-notes/pages/5-1-4.adoc
> +* Fixed various Hazelcast Cloud integration issues. [MC-1591]
it doesn't affect the end user at all. It's just an internal Hazelcast Clout to MC integration.

2022-07-05 10:56 UTC, promanenko commented on docs/modules/release-notes/pages/5-1-4.adoc
> +* Jet metrics storage stores only Jet-related metrics. [MC-1532]
`Jet metrics storage stores only Jet-related metrics leading to less memory consumption.` - is it OK?

2022-07-05 11:02 UTC, JakeSCahill commented on docs/modules/release-notes/pages/5-1-4.adoc
> +* Jet metrics storage stores only Jet-related metrics. [MC-1532]
So previously, we were storing unrelated metrics in Jet metrics storage? Isn't that a bug fix?

`We no longer store unrelated metrics with Jet metrics, leading to less memory consumption.`?

2022-07-05 11:17 UTC, promanenko commented on docs/modules/release-notes/pages/5-1-4.adoc
> +* Jet metrics storage stores only Jet-related metrics. [MC-1532]
moved to the bugfixes block

2022-07-05 11:18 UTC, JakeSCahill approved these changes

2022-07-05 11:18 UTC, merged