MC-1438 Integrate MapBrowser into SQL Browser
hazelcast/management-center-docs pull request #189
Opened 2022-08-22 12:38 UTC by Sodik

2022-08-25 12:41 UTC, promanenko commented
please update screenshots with the new design without "show first/show last ..." radiobuttons

2022-08-25 13:25 UTC, promanenko commented on docs/modules/tools/pages/sql-browser.adoc
>  You can view results in two modes:
please remove the information about modes or state that they are applicable only to pre-5.2 clusters

2022-08-25 13:25 UTC, promanenko commented on docs/modules/tools/pages/sql-browser.adoc
> +If you run *simple SELECT queries (without JOIN and AGGREGATION)* over IMap Mappings then you can get access to xref:data-structures:map.adoc#map-browser[query medata].
query medata -> entry metadata?

2022-08-25 13:25 UTC, promanenko commented on docs/modules/tools/pages/sql-browser.adoc
> +By clicking on *chevron button* at the beginning of each SQL result table row, metadata view opens below a row
is it `chevron button` or `chevron sign`?

2022-08-25 13:25 UTC, promanenko commented on docs/modules/tools/pages/sql-browser.adoc
> +image:ROOT:SQLBrowserQueryResultTabWithOpenMapBrowser.png[A list of query results with metada view]
metada -> metadata?

2022-08-25 16:29 UTC, Sodik commented on docs/modules/tools/pages/sql-browser.adoc
>  You can view results in two modes:
removed

2022-08-25 16:29 UTC, Sodik commented on docs/modules/tools/pages/sql-browser.adoc
> +If you run *simple SELECT queries (without JOIN and AGGREGATION)* over IMap Mappings then you can get access to xref:data-structures:map.adoc#map-browser[query medata].
changed

2022-08-25 16:30 UTC, Sodik commented on docs/modules/tools/pages/sql-browser.adoc
> +By clicking on *chevron button* at the beginning of each SQL result table row, metadata view opens below a row
button with chevron icon

2022-08-25 16:31 UTC, Sodik commented on docs/modules/tools/pages/sql-browser.adoc
> +image:ROOT:SQLBrowserQueryResultTabWithOpenMapBrowser.png[A list of query results with metada view]
done

2022-08-26 09:43 UTC, JakeSCahill requested changes

2022-08-26 09:43 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +image:ROOT:SQLBrowserQueryResultTabWithOpenMapBrowser.png[A list of query results with metadata view]
This image displays a -1 for *Hits*. Is this expected?

2022-08-26 09:43 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +=== Map browser
```suggestion
=== Viewing Map Metadata
```

2022-08-26 09:43 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +If you run *simple SELECT queries (without JOIN and AGGREGATION)* over IMap Mappings then you can get access to xref:data-structures:map.adoc#map-browser[entry metadata].
```suggestion
If you run simple `SELECT` queries without joins or aggregations over maps, you can view xref:data-structures:map.adoc#map-browser[metadata] for each entry that is returned by the query.
```

2022-08-26 09:43 UTC, JakeSCahill commented on docs/modules/tools/pages/sql-browser.adoc
> +By clicking on *button with chevron icon* at the beginning of each SQL result table row, metadata view opens below a row
```suggestion
To view an entry's metadata, click the chevron (*⌄*) button next to a map entry in the query results.
```

2022-08-26 12:58 UTC, promanenko commented on docs/modules/tools/pages/sql-browser.adoc
> +image:ROOT:SQLBrowserQueryResultTabWithOpenMapBrowser.png[A list of query results with metadata view]
it is a known bug on the member side, to be fixed before 5.2 release https://hazelcast.atlassian.net/browse/HZ-1313
@Sodik could you attach a screenshot with non-negative Hits value? it should work fine if there is a single member

2022-08-26 13:13 UTC, promanenko approved these changes

2022-08-26 13:24 UTC, merged

2022-08-26 13:25 UTC, JakeSCahill commented
We should backport this to the `v/5.2-BETA-1` branch