MС-1680 - system/env properties update for 5.2
hazelcast/management-center-docs pull request #193
Opened 2022-08-31 15:02 UTC by promanenko

- properties introduced in 5.2
- few missing metric storage properties
- LDAP SSL properties
- AD SSL properties

2022-08-31 16:18 UTC, JakeSCahill requested changes

2022-08-31 16:18 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/active-directory.adoc
> +For all the Active Directory SSL configuration options, see xref:deploy-manage:system-properties.adoc[].
I think we can remove the duplicated properties from this section and just provide this sentence and the link.

2022-08-31 16:18 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/active-directory.adoc
> +For all the Active Directory SSL configuration options, see xref:deploy-manage:system-properties.adoc[].
```suggestion
See the xref:deploy-manage:system-properties.adoc#hazelcast-mc-ad-ssl-protocol[SSL configuration options] for Active Directory.
```

2022-08-31 16:18 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/ldap.adoc
> +For all the LDAP SSL configuration options, see xref:deploy-manage:system-properties.adoc[].
Same comment as for AD.

2022-08-31 16:18 UTC, JakeSCahill commented on docs/modules/deploy-manage/pages/ldap.adoc
> +For all the LDAP SSL configuration options, see xref:deploy-manage:system-properties.adoc[].
```suggestion
See the xref:deploy-manage:system-properties.adoc#hazelcast-mc-ldap-ssl-protocol[SSL configuration options] for LDAP.
```

2022-08-31 18:33 UTC, promanenko commented on docs/modules/deploy-manage/pages/active-directory.adoc
> +For all the Active Directory SSL configuration options, see xref:deploy-manage:system-properties.adoc[].
reworked the block

2022-08-31 18:34 UTC, promanenko commented on docs/modules/deploy-manage/pages/ldap.adoc
> +For all the LDAP SSL configuration options, see xref:deploy-manage:system-properties.adoc[].
reworked the block

2022-09-02 08:54 UTC, Serdaro approved these changes

2022-09-02 08:59 UTC, merged