MC-1700 Docs for Index stats table
hazelcast/management-center-docs pull request #195
Opened 2022-09-08 15:03 UTC by aberatcan

- Added map index stats table section to the maps page
- Updated monitoring maps screenshot for the new feature
- Added new screenshots

2022-09-09 09:50 UTC, Serdaro approved these changes
Approving with some suggested changes.

2022-09-09 09:50 UTC, Serdaro commented on docs/modules/data-structures/pages/map.adoc
> +NOTE: You need to create index to see this table here. See the xref:{page-latest-supported-hazelcast}@hazelcast:query:indexing-maps.adoc[Indexing Maps] for details
... create indexes to see ...   ... for details.

2022-09-09 09:50 UTC, Serdaro commented on docs/modules/data-structures/pages/map.adoc
> +To see more details about an index, click on the down arrow next to the index name.
Let's remove this line, and rephrase it as suggested in the next review comment below.

2022-09-09 09:50 UTC, Serdaro commented on docs/modules/data-structures/pages/map.adoc
> +
Maybe it is better to insert the "Table-2" image here, with a text as follows:

You can see more details about an index by clicking on the down arrow next to the index name:

((Table-2 image))

From left to right this table lists the following:

2022-09-09 11:26 UTC, aberatcan commented on docs/modules/data-structures/pages/map.adoc
> +
These two table images belong to the same table. Couldn't be able to take a screenshot of all columns of the map index stats table because it has 13 columns. I divided it two images to display all the columns.

2022-09-12 11:12 UTC, promanenko commented on docs/modules/data-structures/pages/map.adoc
> +image:ROOT:MapIndexStatsTable.png[Map Index Stats Table]
I don't think we should post two images to show all the columns in the table.
I think a single image will be enough.
@JakeSCahill WDYT?

2022-09-12 11:12 UTC, promanenko commented on docs/modules/data-structures/pages/map.adoc
> +**Map Index Stats Table** provides information about Map Index statistics if there exists any index for this map.
`if there exists any index` - is this grammatically correct?

2022-09-12 11:31 UTC, aberatcan commented on docs/modules/data-structures/pages/map.adoc
> +**Map Index Stats Table** provides information about Map Index statistics if there exists any index for this map.
you are right `if there is any `  would be better 👍

2022-09-12 12:07 UTC, JakeSCahill commented on docs/modules/data-structures/pages/map.adoc
> +NOTE: You need to create indexes to see this table here. See the xref:{page-latest-supported-hazelcast}@hazelcast:query:indexing-maps.adoc[Indexing Maps] for details.
```suggestion
NOTE: This table is displayed only if the map has at least one index. To learn how to create indexes, see xref:{page-latest-supported-hazelcast}@hazelcast:query:indexing-maps.adoc)[Indexing Maps] in the Hazelcast Platform documentation.
```

2022-09-12 12:08 UTC, JakeSCahill commented on docs/modules/data-structures/pages/map.adoc
> +image:ROOT:MapIndexStatsTable.png[Map Index Stats Table]
I think we don't even need a screenshot here. We provide the information in the table.

2022-09-12 12:09 UTC, JakeSCahill commented on docs/modules/data-structures/pages/map.adoc
> +.Map Index Stats Table Fields
```suggestion
.Top-level fields for map index statistics
```

2022-09-12 12:10 UTC, JakeSCahill commented on docs/modules/data-structures/pages/map.adoc
> +.Map Index Stats Table Detailed Sub Row Fields
```suggestion
.Second-level fields for map index statistics
```

2022-09-12 12:37 UTC, JakeSCahill commented on docs/modules/data-structures/pages/map.adoc
> +You can see more details about an index by clicking on the down arrow next to the index name.
```suggestion
You can see member-level statistics for each index by clicking on the down arrow next to the index name.
```

2022-09-12 12:38 UTC, JakeSCahill commented on docs/modules/data-structures/pages/map.adoc
> +|Creation time of the index for the first time among the members.
How is this different compared to the member-level view?

2022-09-12 12:42 UTC, aberatcan commented on docs/modules/data-structures/pages/map.adoc
> +|Creation time of the index for the first time among the members.
It's the smallest creation time among the members. In the member-level, it is creation time of index in that member.

2022-09-12 12:47 UTC, JakeSCahill requested changes
Some comments and suggestions.

2022-09-12 13:17 UTC, aberatcan commented on docs/modules/data-structures/pages/map.adoc
> +image:ROOT:MapIndexStatsTable.png[Map Index Stats Table]
I think we need it at least one of them. it's nice to see the table when you are reading the provided information and in addition to that all other tables have their own screenshots. We should follow the pattern, imho.

2022-09-12 15:14 UTC, JakeSCahill commented on docs/modules/data-structures/pages/map.adoc
> +|Creation time of the index for the first time among the members.
```suggestion
|The first time that the index was created on a member in the cluster.
```

2022-09-13 11:39 UTC, JakeSCahill approved these changes

2022-09-13 11:39 UTC, JakeSCahill commented
Please backport to the v/5.2-BETA-1 branch

2022-09-13 13:42 UTC, merged