MC-1677 SQL Browser 5.2 docs update
hazelcast/management-center-docs pull request #201
Opened 2022-09-19 08:10 UTC by aberatcan

- Added create mapping section to SQL Browser page.

2022-09-19 09:53 UTC, promanenko commented on docs/modules/tools/pages/sql-browser.adoc
> +To create mapping for *Hazelcast Map*, after selecting the connector type as `Create Mapping for Hazelcast Map`, select the name of an existing map from the dropdown:
only maps that don't have any mappings are shown in the dropdown

2022-09-20 12:38 UTC, Serdaro requested changes
Minor editing suggestions.

2022-09-20 12:38 UTC, Serdaro commented on docs/modules/tools/pages/sql-browser.adoc
> +and then select the type of the mapping that you want to create from the dropdown:
You can generate `CREATE MAPPING` statements automatically using Management Center's connector wizard. Using this wizard, you can create mappings with the connectors for Hazelcast Platform maps, Kafka, and other file systems. Launch the wizard by clicking the **Connector Wizard** button, and see the following sections for each connector type.
and then select the type of the mapping that you want to create from the dropdown:

2022-09-20 12:38 UTC, Serdaro commented on docs/modules/tools/pages/sql-browser.adoc
> +To create mapping for *Hazelcast Map*, after selecting the connector type as `Create Mapping for Hazelcast Map`, select the name of an existing map from the dropdown. Only maps that don't have any ma
(Let's put a new line between the heading and its body content, and make the body content as a bulleted list)

=== Create a Mapping for Hazelcast Maps

. Select the connector type as **Create Mapping for Hazelcast Map**.
. Select the name of an existing map from the dropdown; only maps that don't have any mappings are shown.

2022-09-20 12:38 UTC, Serdaro commented on docs/modules/tools/pages/sql-browser.adoc
> +To create mapping for *Kafka*, after selecting the connector type as `Create Mapping for Kafka`, fill out the newly opened form. While you are filling this form, editor would be updated appropriately
(Let's put a new line between the heading and its body content, and make the body content as a bulleted list)

=== Create a Mapping for Kafka

. Select the connector type as **Create Mapping for Kafka**.
. Fill out the newly opened form. While you are filling this form, the editor should be updated appropriately.

2022-09-20 12:38 UTC, Serdaro commented on docs/modules/tools/pages/sql-browser.adoc
> +To create mapping for a *File System*, after selecting the connector type as `Create Mapping for a File System`, fill out the newly opened form. While you are filling this form, editor would be updat
(Let's put a new line between the heading and its body content, and make the body content as a bulleted list)

=== Create a Mapping for a File System

. Select the connector type as **Create Mapping for a File System**.
. Fill out the newly opened form. While you are filling this form, the editor should be updated appropriately.

2022-09-20 13:08 UTC, Serdaro approved these changes

2022-09-20 13:34 UTC, merged