5.3.2 release notes
hazelcast/management-center-docs pull request #268
Opened 2023-08-08 13:50 UTC by promanenko

2023-08-08 13:53 UTC, zhmaeff approved these changes

2023-08-08 13:53 UTC, zhmaeff commented on docs/modules/release-notes/pages/5-3-2.adoc
> +* Jetty SNI check is disabled by default. [MC-2276]
```suggestion
* Jetty SNI host check is disabled by default. [MC-2276]
```

2023-08-08 13:53 UTC, utkukaratas commented on docs/modules/release-notes/pages/5-3-2.adoc
> +* Improved database error messages. [MC-2063]
haha we actually made them worse by suppressing them for security :)))

2023-08-08 13:53 UTC, utkukaratas approved these changes

2023-08-09 08:54 UTC, angelasimms requested changes
Just some minor amends/queries?

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +** Added an ability to see a query from Query history without execution. [MC-2091]
```suggestion
** Added the ability to view a query from the query history. [MC-2091]
```
Is this what you mean? Otherwise it reads like you can just type a query in the browser and then it is saved in the query history?

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +** Updated texts in Data Explorer. [MC-2224]
```suggestion
** Updated UI text on the welcome screen of the Data Explorer. [MC-2224]
```

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +* Now a banner is displayed when repartitioning is in progress. [MC-2132]
```suggestion
* A banner is now displayed when repartitioning is in progress. [MC-2132]
```

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +* Jetty SNI host check is disabled by default. [MC-2276]
```suggestion
* Jetty SNI host check is now disabled by default. [MC-2276]
```

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +** Fixed primary key violation on a simultaneous executions of multiple queries. [MC-2050]
```suggestion
** Fixed a primary key violation that occurred when executing multiple simultaneous queries. [MC-2050]
```

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +* Fixed incorrect Jet metrics during the first minute after MC is connected. [MC-1578]
```suggestion
* Fixed incorrect Jet metrics that were displayed one minute after connecting to MC. [MC-1578]
```

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +* Fixed false positive HeathCheck warnings for maps created from a default config. [MC-2226]
```suggestion
* Fixed false positive HealthCheck warnings for maps created using the default configuration. [MC-2226]
```

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +* MC no longer blocks HTTP calls when a member config is not available. [MC-2250] [MC-2259]
```suggestion
* MC no longer blocks HTTP calls when a member configuration is unavailable. [MC-2250] [MC-2259]
```

2023-08-09 08:54 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +* MC no longer throws an exception when WAN publisher name is not set. [MC-2249]
```suggestion
* MC no longer throws an exception when the WAN publisher name is not set. [MC-2249]
```

2023-08-09 09:15 UTC, promanenko commented on docs/modules/release-notes/pages/5-3-2.adoc
> +** Added an ability to see a query from Query history without execution. [MC-2091]
yes, previously if user wanted to see the historical query it was automatically executed again. Now it's possible just view it

2023-08-09 09:51 UTC, angelasimms commented on docs/modules/release-notes/pages/5-3-2.adoc
> +** Added an ability to see a query from Query history without execution. [MC-2091]
So maybe something like this?

Added the ability to view a query from the query history. The query is no longer automatically executed.

2023-08-09 14:14 UTC, promanenko commented on docs/modules/release-notes/pages/5-3-2.adoc
> +** Added an ability to see a query from Query history without execution. [MC-2091]
agree, updated

2023-08-09 14:16 UTC, angelasimms approved these changes
LGTM

2023-08-09 15:03 UTC, merged