MC-2553 Documentation for Terminating CP Session from MC
hazelcast/management-center-docs pull request #285
Opened 2024-01-02 13:31 UTC by aberatcan

Documentation update for [MC-1719](https://hazelcast.atlassian.net/browse/MC-1719)
- added new section to CP Subsystem Dashboard and updated screenshots

2024-01-02 13:52 UTC, arodionov commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +If a Hazelcast instance that owns a CP session is not temporarily partitioned and crashed, its session could be closed manually to release its resources immediately.
The owner of a CP session is a _caller_ (a Hazelcast member or client that interacts with the CP Subsystem through APIs - https://docs.hazelcast.com/hazelcast/5.3/cp-subsystem/cp-subsystem#glossary)
So, we should talk here about partitioning or crashing the _caller_

2024-01-02 14:03 UTC, aberatcan commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +If a Hazelcast instance that owns a CP session is not temporarily partitioned and crashed, its session could be closed manually to release its resources immediately.
There is no mention for _caller_ in MC docs. We need to describe the _caller_ for the user here. We can use `session owner` instead of _caller_ like this:
```suggestion
If a session owner is not temporarily partitioned and crashed, its session could be closed manually to release its resources immediately.
```

2024-01-02 14:14 UTC, arodionov commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +If a Hazelcast instance that owns a CP session is not temporarily partitioned and crashed, its session could be closed manually to release its resources immediately.
I am fine with this term.

2024-01-02 14:16 UTC, arodionov approved these changes
Thanks for the work!

2024-01-03 09:34 UTC, rebekah-lawrence requested changes

2024-01-03 09:34 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +If a session owner is not temporarily partitioned and crashed, its session could be closed manually to release its resources immediately.
```suggestion
If a session owner is not temporarily partitioned and crashed, an admin user can manually close the session to release its resources immediately.
```

2024-01-03 09:34 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +This action is available only to admin users.
```suggestion

```

2024-01-03 09:34 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +
To manually close the session, complete the following steps:

2024-01-03 09:34 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +. Go to *CP Subsystem* > *Dashboard*.
```suggestion
. Select *CP Subsystem* > *Dashboard*.
```

2024-01-03 09:34 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +. Find the CP session that you want to close from the CP Session Metrics Table.
```suggestion
. In the CP Session Metrics Table, find the CP session that you want to close.
```

2024-01-03 09:34 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +. Click `Terminate` button in the Actions column for the related session.
```suggestion
. Select the `Terminate` button in the Actions column for the related session.
```

2024-01-03 09:34 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +If everything goes well, a success message is displayed.
```suggestion
If the session is successfully closed, a confirmation message displays.
```

2024-01-03 09:34 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +If an exception occurs, an error notification is displayed.
```suggestion
If an exception occurs, an error displays.
```

2024-01-03 14:29 UTC, rebekah-lawrence approved these changes
Just a small formatting update, otherwise, it looks good to me.

Thank you.

2024-01-03 14:29 UTC, rebekah-lawrence commented on docs/modules/cp-subsystem/pages/dashboard.adoc
> +. Select the `Terminate` button in the Actions column for the related session.
```suggestion
. Select the *Terminate* button in the Actions column for the related session.
```

2024-01-04 14:04 UTC, promanenko approved these changes

2024-01-04 14:06 UTC, merged