CLC console documentation [MC-2390]
hazelcast/management-center-docs pull request #287
Opened 2024-01-10 14:30 UTC by mehmettokgoz

2024-01-10 14:56 UTC, rebekah-lawrence requested changes

2024-01-10 14:56 UTC, rebekah-lawrence commented on docs/modules/tools/pages/console.adoc
> +:description: The console feature enables you to execute client operations using built-in Hazelcast Command-Line Client (CLC).
```suggestion
:description: The console feature allows you to execute client operations using the built-in Hazelcast Command-Line Client (CLC).
```

2024-01-10 14:56 UTC, rebekah-lawrence commented on docs/modules/tools/pages/console.adoc
> +For more information on these features, visit: https://docs.hazelcast.com/clc/latest/overview
```suggestion
For further information on these features, refer to the https://docs.hazelcast.com/clc/latest/overview[Overview^] topic of the CLC documentation.
```

2024-01-10 14:56 UTC, rebekah-lawrence commented on docs/modules/tools/pages/console.adoc
> +. Execute any SQL query in terminal. You don't need to use any prefix for SQL queries.
```suggestion
. Execute any SQL query in the terminal. Do not prefix SQL queries.
```

2024-01-10 14:56 UTC, rebekah-lawrence commented on docs/modules/tools/pages/console.adoc
> +. Execute CLC commands with `\` prefix, e.g. `\atomic-long`.
```suggestion
. Prefix CLC commands with `\`. For example, `\atomic-long`.
```

2024-01-10 14:56 UTC, rebekah-lawrence commented on docs/modules/tools/pages/console.adoc
> +You can use `--help` prefix with all commands to get more detail.
```suggestion
You can use the `--help` option with any command to view the help for that command.
```

2024-01-10 14:56 UTC, rebekah-lawrence commented on docs/modules/tools/pages/console.adoc
> +TIP: Console container is resizable, you can change the height by dragging upper bar.
```suggestion
TIP: The console container is resizable; to change the height, drag the top bar.
```

2024-01-10 14:56 UTC, rebekah-lawrence commented on docs/modules/tools/pages/console.adoc
> +You can make it fullscreen or minimized using the icons in the top-right corner of console container.
```suggestion
You can maximize or minimize the console container using the icons in its top-right corner.
```

2024-01-11 10:04 UTC, promanenko approved these changes

2024-01-11 11:12 UTC, rebekah-lawrence approved these changes
LGTM

2024-01-11 12:18 UTC, merged