Update docs with new Healthcheck information
hazelcast/management-center-docs pull request #296
Opened 2024-02-08 20:02 UTC by emrberk

- Healthcheck page is updated with the new information and screenshots.
- Dashboard page is updated with new screenshots.
- Configuration Healthcheck wording is changed to Healthcheck.
- Removed the information about Periodic Healthcheck Runner.

2024-02-12 14:20 UTC, promanenko commented on docs/modules/clusters/pages/healthcheck.adoc
> +Healthcheck categorizes the checks and problems with five different severities:
I think severities are only FAIL/WARNING/INFO which indicate `non pass` status.
PASS and DISABLED are two other types of status

2024-02-12 14:20 UTC, promanenko commented on docs/modules/clusters/pages/healthcheck.adoc
> +- *FAIL:* A check has the status `FAIL`, indicated by a red color, when the cluster exhibits at least one critical problem, signaling the need for urgent resolution to prevent system failure or compr
nit: I think `system failure` is a too strong wording here. For instance mismatching map config doesn't lead to cluster shutdown, but to an unpredicted behaviour and possibly functional problems. 
@jgardiner68 do you have an idea how to phrase it correctly?

2024-02-12 14:20 UTC, promanenko commented on docs/modules/clusters/pages/healthcheck.adoc
> +NOTE: Disabling for a specific data structure works only for specific checks. This mechanism does not exist for every check.
This mechanism does not exist for every check. => There is no mechanism to disable all checks for a particular data structure.

2024-02-12 17:28 UTC, rebekah-lawrence requested changes

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +A check can be disabled when it is not critical, and omitting the check is feasible for a cluster. When a check is disabled, Healthcheck does not perform an operation about this particular check.
```suggestion
Only disable a check when it is not critical and when omitting that check is viable for a cluster. When a check is disabled, Healthcheck does not perform that check.
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +Healthcheck provides two disabling mechanisms:
```suggestion
You can disable Healthcheck in either of the following ways:
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +*Disabling for the whole cluster:* A check can be disabled for the whole cluster by clicking on the checkbox in the details of a report item. Cluster-wide disabled check will not be performed on any
```suggestion
* *Disable for the whole cluster:* Select the checkbox in the details of a report item to disable the check for the whole cluster . If selected, the check is not performed on any member or data structure in the cluster.
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +*Disabling for a specific data structure:* A check can be disabled for a specific data structure by clicking on the `Disable For` button inside a problem detail. Note that the check will be performed
```suggestion
* *Disable for a specific data structure*: Select the *Disable For* button in the problem details to disable the check for a specific data structure. 
+
NOTE: The other data structures are checked,
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +and it may still contain problems about other data structures.
```suggestion
and can identify problems with other data structures including the one for which the check has been disabled.
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +NOTE: Disabling for a specific data structure works only for specific checks. This mechanism does not exist for every check.
```suggestion
You can only disable a specific check for a data structure; you cannot disable all checks for that data structure.
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +
```suggestion
+
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +Disabling a check causes the corresponding report item to move down the list. The details of a disabled check looks like the following:
```suggestion
When a check is disabled, the corresponding report item moves down the list. The details of a disabled check are similar to the following:
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +A check may be further enabled for the whole cluster, or for a specific data structure from the report details of the disabled check.
```suggestion
You can enable a check for the whole cluster, or for a specific data structure, from the report details of the disabled check.
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +A check may be further enabled for the whole cluster, or for a specific data structure from the report details of the disabled check.
Just a question: 

I presume that historic check reports are retained, and this is how you can select a report for a disabled check. If the check is disabled before Healthcheck is ever run (if this is possible), there would be no report.

Is there any situation in which a disabled check would not have an existing report through which it can be re-enabled?

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +- If a check is disabled cluster-wide, the checkbox inside the report details can be used to enable the check for the whole cluster.
```suggestion
- If a check is disabled cluster-wide, deselect the checkbox in the report details to enable the check for the whole cluster.
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +- If a check is disabled for a specific data structure, details about the disabled data structures is shown in the report item. You can further enable the check for a specific data structure by click
```suggestion
- If a check is disabled for a specific data structure, select the *Enable For* button in the report details to enable the check for that data structure.
```

2024-02-12 17:28 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +the problem details.
```suggestion

```

2024-02-13 15:30 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +- *FAIL:* A check has the status `FAIL`, indicated by a red color, when the cluster exhibits at least one critical problem, signaling the need for urgent resolution to prevent system failure or compr
I changed it with "when the cluster exhibits at least one critical problem that may result in an unexpected behavior or an issue with the designed functionality." WDYT?

2024-02-13 15:30 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +Healthcheck categorizes the checks and problems with five different severities:
I changed the sentence. Can you please take a look at it again?

2024-02-13 15:31 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +NOTE: Disabling for a specific data structure works only for specific checks. This mechanism does not exist for every check.
Changed it with the suggestion.

2024-02-13 15:31 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +Healthcheck results can be filtered by searching for check ID, description, problematic member, and data structure.
I made the change, but used "or" instead of "and/or". We choose only one of these options.

2024-02-13 15:31 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +and advice to fix the issue.
"advice" is a special term in Healthcheck. I used "and an advice to fix the issue"

2024-02-13 15:32 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +Healthcheck provides two disabling mechanisms:
I added this one, as "You can disable a check in either of the following ways:".
Healthcheck is a general term.

2024-02-13 15:32 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +and it may still contain problems about other data structures.
I guess this "Note that" part is not needed completely :/ I removed it.

2024-02-13 15:32 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +NOTE: Disabling for a specific data structure works only for specific checks. This mechanism does not exist for every check.
What I meant here is closer to the Pavlo's suggestion here: https://github.com/hazelcast/management-center-docs/pull/296#discussion_r1486248363
I changed it.

2024-02-13 15:32 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +
Is this a leftover?

2024-02-13 15:32 UTC, emrberk commented on docs/modules/clusters/pages/healthcheck.adoc
> +A check may be further enabled for the whole cluster, or for a specific data structure from the report details of the disabled check.
We don't retain historical check reports. We maintain a fixed check list, and keep record of the disabled check list of the user. So, whenever the user gets a Healthcheck report, they get all of the disabled checks and report items, through which they can re-enable the check.

2024-02-13 15:34 UTC, emrberk commented
Hi @rebekah-lawrence , thanks for the review. I resolved the conversations that I applied exactly the same suggestion. There are several left with my comments.

2024-02-13 16:26 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +A check may be further enabled for the whole cluster, or for a specific data structure from the report details of the disabled check.
Fantastic, and thank you for explaining.

2024-02-13 16:31 UTC, rebekah-lawrence approved these changes
LGTM

And thank you - for the contribution and for answering my questions.

2024-02-13 16:31 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/healthcheck.adoc
> +
I had suggested making the points a list - to keep the note in-line with the list item you need to connect the lines with a plus. It is just formatting for the compiler.

If not making them a list, you don't need the plus.

2024-02-16 10:30 UTC, promanenko approved these changes

2024-02-16 10:35 UTC, merged