MC-2655 - update map config limitations
hazelcast/management-center-docs pull request #298
Opened 2024-02-12 14:56 UTC by promanenko

The screenshot will be updated in https://hazelcast.atlassian.net/browse/MC-2640

2024-02-12 15:26 UTC, rebekah-lawrence requested changes

2024-02-12 15:26 UTC, rebekah-lawrence commented on docs/modules/data-structures/pages/map.adoc
> +NOTE: Map config is updated only on the members MC is aware of at the time of the update. When a new member joins the cluster, the updated map configuration is not propagated to it.
```suggestion
NOTE: The Map configuration is updated only on the members that Management Center is aware of at the time of the update. When a new member joins the cluster, the updated map configuration is not propagated to it.
```

2024-02-12 15:26 UTC, rebekah-lawrence commented on docs/modules/data-structures/pages/map.adoc
> +Also if a member has persistence enabled, the updated map config is not persisted to disk and the updates are lost upon the next restart.
```suggestion
If a member has persistence enabled, the updated map configuration is not persisted to disk and the updates are lost on the next restart.
```

2024-02-13 09:17 UTC, vbekiaris approved these changes

2024-02-13 11:32 UTC, merged