Align docs with MC 5.4.0
hazelcast/management-center-docs pull request #305
Opened 2024-03-12 17:53 UTC by emrberk

- Screenshots are updated with rebranding.
- Top Bar and Side Bar updates are added.
- License pages are updated.
- Some tables are updated.
- Removed legacy features.
- Removed screenshots about legacy features.

2024-03-13 09:42 UTC, rebekah-lawrence reviewed
Before I can do a proper review, I need to understand why the change in name from toolbar and menu to Top Bar and Side Bar. 

I do not see this change as providing any further information to users - potentially Title Bar and Side Navigation are clearer, or even Top Menu and Side Menu/Navigation. In fact, we don't really have to name the toolbar (and I agree, it isn't a toolbar), we can just say Select x, located at the top of the screen, or Select x from the options at the top of the screen.

In general, however, these must be referred to as "the x Bar", not just "x Bar"

This will be a job for the IA/style guide/doc improvements. Noting for @docs team; nothing for you to do. Click ought to be changed to Select throughout. However, I see that Click is used across the MC docs, so it is not worth changing in just these updates. In the same area, per is Latin, ought to be for each.

2024-03-13 10:18 UTC, emrberk commented
> Before I can do a proper review, I need to understand why the change in name from toolbar and menu to Top Bar and Side Bar.
> 
> I do not see this change as providing any further information to users - potentially Title Bar and Side Navigation are clearer, or even Top Menu and Side Menu/Navigation. In fact, we don't really have to name the toolbar (and I agree, it isn't a toolbar), we can just say Select x, located at the top of the screen, or Select x from the options at the top of the screen.
> 
> In general, however, these must be referred to as "the x Bar", not just "x Bar"
> 
> This will be a job for the IA/style guide/doc improvements. Noting for @docs team; nothing for you to do. Click ought to be changed to Select throughout. However, I see that Click is used across the MC docs, so it is not worth changing in just these updates. In the same area, per is Latin, ought to be for each.

Hi Rebekah,

Top Bar (previously referred as Toolbar) does not contain any tools but selecting cluster right now. That's why I changed the naming here. Side Bar contains SQL browser and Console buttons as well as Menu. So, We can't call it "menu" now, because Menu is just a part of Side Bar and can be opened/closed. Side Bar and Top Bar may not be the best naming, and one can come up with better names for them. I just referred them as in our repository, so feel free to revise it.
Luckily, we don't have so many text updates in this PR, but mostly screenshots :)

2024-03-13 11:06 UTC, rebekah-lawrence commented
I've requested @pawelklasa's review - he will doubtless have better ideas than I on how we should refer to the UI elements.

2024-03-13 11:23 UTC, jgardiner68 commented
@emrberk Screen shots look good.   The bulk are updated images but there are more deletions than additions.  Have we confirmed that this is not removing useful images from the docs?

2024-03-13 11:32 UTC, jgardiner68 commented on docs/modules/data-structures/pages/map.adoc
Backups, Locks and Dirty Entries are still available but have been added to another view to simplify the layout.

2024-03-13 11:33 UTC, jgardiner68 commented on docs/modules/clusters/pages/clients.adoc
> -|Enterprise
Why has this been removed?  IIRC we still have EE and non-EE Java clients (The change was to merge the Enterprise column into another column)

2024-03-13 11:35 UTC, jgardiner68 commented on docs/modules/clusters/pages/cluster-license.adoc
> -- *License Type*: The type of license.
has this info been moved elsewhere?

2024-03-13 11:36 UTC, jgardiner68 commented on docs/modules/cp-subsystem/pages/atomic-ref.adoc
> -An atomic reference has only a single metric: Its name.
This is to avoid tickets about there being less detail -- I think it should be kept.

2024-03-13 11:37 UTC, jgardiner68 commented on docs/modules/data-structures/pages/map.adoc
> -|Backups
Moved to a different view

2024-03-13 11:37 UTC, jgardiner68 commented on docs/modules/data-structures/pages/map.adoc
> -|Locks
moved to a different view

2024-03-13 11:37 UTC, jgardiner68 commented on docs/modules/data-structures/pages/map.adoc
> -|Max Avg Remove Latency
moved to a different view?

2024-03-13 11:38 UTC, jgardiner68 commented on docs/modules/deploy-manage/pages/updating-mc-license-ui.adoc
> -Warnings are displayed when a license expires within 30 days.
This is still true - where is it captured?

2024-03-13 11:41 UTC, jgardiner68 requested changes
Concerned that some sections have been removed from the docs whereas those columns have been moved to different views in the same table.  This should be explained.

Is there a doc page to explain the Licensed Features page?

2024-03-13 13:09 UTC, emrberk commented on docs/modules/data-structures/pages/map.adoc
Added them again, please take a look.

2024-03-13 13:09 UTC, emrberk commented on docs/modules/clusters/pages/clients.adoc
> -|Enterprise
They are merged to "Type" column, shown as "Java Enterprise". So this column does not exist anymore.

2024-03-13 13:09 UTC, emrberk commented on docs/modules/clusters/pages/cluster-license.adoc
> -- *License Type*: The type of license.
It doesn't exist anymore, at least not in this page.

2024-03-13 13:09 UTC, emrberk commented on docs/modules/cp-subsystem/pages/atomic-ref.adoc
> -An atomic reference has only a single metric: Its name.
All CP data structures have name and group columns, but we don't refer to them as metrics. I think it makes sense not to refer name as metric.

2024-03-13 13:09 UTC, emrberk commented on docs/modules/data-structures/pages/map.adoc
> -|Backups
Added.

2024-03-13 13:09 UTC, emrberk commented on docs/modules/data-structures/pages/map.adoc
> -|Locks
Added.

2024-03-13 13:09 UTC, emrberk commented on docs/modules/data-structures/pages/map.adoc
> -|Max Avg Remove Latency
Not even in a different view, added it again.

2024-03-13 13:09 UTC, emrberk commented on docs/modules/deploy-manage/pages/updating-mc-license-ui.adoc
> -Warnings are displayed when a license expires within 30 days.
Added it again, in the same section.

2024-03-13 13:14 UTC, emrberk commented
> Concerned that some sections have been removed from the docs whereas those columns have been moved to different views in the same table. This should be explained.
> 
> Is there a doc page to explain the Licensed Features page?

Addressed the review comments about the removed columns. We don't have a doc page for promo.

2024-03-15 10:27 UTC, rebekah-lawrence approved these changes
Language is consistent with other MC content. Approving.

2024-03-15 11:37 UTC, jgardiner68 approved these changes

2024-03-18 13:09 UTC, emrberk commented on docs/modules/data-structures/pages/map.adoc
> +|Removals
The table column is named as "Removals". In other data structure pages, we also refer to it as "Removals", despite having "Removes/s" in throughput statistics. That's why I put "Removals" here.

2024-03-18 13:09 UTC, emrberk commented on docs/modules/data-structures/pages/map.adoc
> +|Removals
>Wht about Backups, Backup Memory, Locks, Dirty Caches

Can you elaborate?

2024-03-18 13:19 UTC, emrberk commented on docs/modules/clusters/pages/clients.adoc
> -|Enterprise
Added the description about Enterprise to Type column, can you please take a look at it?

2024-03-18 13:20 UTC, emrberk commented on docs/modules/clusters/pages/clients.adoc
> -|Enterprise
>What happened to client labels?

It exists in Client Labels View. Explanation is still present.

2024-03-18 13:37 UTC, pawelklasa approved these changes

2024-03-20 12:40 UTC, merged