MC-2715 Client filtering preview
hazelcast/management-center-docs pull request #322
Opened 2024-04-26 12:25 UTC by Sodik

2024-05-02 12:54 UTC, promanenko approved these changes

2024-05-02 13:06 UTC, rebekah-lawrence requested changes
A few minor suggestions

2024-05-02 13:06 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/client-filtering.adoc
> +The deployment of filter lists must be confirmed by clicking the *Confirm Deploy* button in a modal.
```suggestion
The deployment of filter lists must be confirmed by clicking the *Confirm Deploy* button.
```

2024-05-02 13:06 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/client-filtering.adoc
> +This modal provides a summary of clients connectivity after the current filter lists have been applied.
```suggestion
A summary of client connectivity is shown after the current filter lists have been applied.
```

2024-05-02 13:06 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/client-filtering.adoc
> +IMPORTANT: If current filter lists disconnect all clients, the warning (*All clients will be blocked if you apply current client filtering configuration*) will be shown on the top of a modal.
```suggestion
IMPORTANT: If the current filter lists disconnect all clients, the warning (*All clients will be blocked if you apply current client filtering configuration*) will be shown on the top of a modal.
```

2024-05-06 13:38 UTC, anatoly-hazelcast commented on docs/modules/ROOT/images/ClientFilteringDeployConfirmation.png
I'm afraid Connected after and Remain connected is effectively the same as we can't identify potential future clients.
https://hazelcast.atlassian.net/browse/MC-2829

2024-06-14 07:41 UTC, anatoly-hazelcast approved these changes

2024-06-14 07:43 UTC, rebekah-lawrence approved these changes
One teeny tiny suggestion.

Otherwise LGTM, so approving in advance.

2024-06-14 07:43 UTC, rebekah-lawrence commented on docs/modules/clusters/pages/client-filtering.adoc
> +IMPORTANT: If the current filter lists disconnect all clients, the warning (*All clients will be blocked if you apply current client filtering configuration*) will be shown on the top of a modal.
```suggestion
IMPORTANT: If the current filter lists disconnect all clients, the warning (*All clients will be blocked if you apply current client filtering configuration*) is displayed on the top of a modal.
```

2024-06-14 10:07 UTC, merged