Add JSON logging instructions [MC-2844]
hazelcast/management-center-docs pull request #327
Opened 2024-06-03 10:09 UTC by emrberk

2024-06-03 11:52 UTC, promanenko approved these changes

2024-06-03 11:54 UTC, rebekah-lawrence requested changes

2024-06-03 11:54 UTC, rebekah-lawrence commented on docs/modules/deploy-manage/pages/logging.adoc
> +NOTE: For a provided JSON logging template to be effective, you need to activate the `json-logging` profile.
```suggestion
NOTE: To use a custom JSON logging template, you must activate the `json-logging` profile as described above.
```

2024-06-03 11:54 UTC, rebekah-lawrence commented on docs/modules/deploy-manage/pages/logging.adoc
> +NOTE: For a provided JSON logging template to be effective, you need to activate the `json-logging` profile.
I am assuming that it is this instruction that needs to be followed:

> Management Center provides JSON template logging out of the box. To enable JSON logging, you can activate json-logging profile by starting Management Center with the following parameter:

However, this is a bit unclear. If MC provides JSON logging OOTB, why do you need to enable it? Do we mean:

> To use a custom JSON logging template, you must activate the json-logging profile as follows: 
> 
>` Dspring.profiles.active=json-logging`

If so, the note is no longer required.

2024-06-03 12:14 UTC, emrberk commented on docs/modules/deploy-manage/pages/logging.adoc
> +NOTE: For a provided JSON logging template to be effective, you need to activate the `json-logging` profile.
Hi Rebekah, we were following the instructions in https://hazelcast.slack.com/archives/C6YCTD1RA/p1710281406856269 to enable JSON logging in MC. The recent change made it possible to enable it only activating a profile, that's why we use `out of the box`. 
Providing JSON template layout however is only for changing the structure of the JSON logs. So if you don't activate `json-logging` profile, providing a JSON template has no effect, as the logs won't be in JSON format.
We added the note to remove possible confusions in a situation like: not activating the JSON logging profile, but passing a template, and expecting it to  be effective.

2024-06-03 12:40 UTC, rebekah-lawrence commented on docs/modules/deploy-manage/pages/logging.adoc
> +NOTE: For a provided JSON logging template to be effective, you need to activate the `json-logging` profile.
Ahhhh, OK. In that case, I'd suggest a slight change to the OOTB statement:

Hazelcast Platform provides JSON template logging out of the box. However, to enable JSON template logging in Management Centre you must activate a profile. To activate a json-logging profile, start Management Center with the following parameter:

2024-06-03 13:32 UTC, emrberk commented on docs/modules/deploy-manage/pages/logging.adoc
> +NOTE: For a provided JSON logging template to be effective, you need to activate the `json-logging` profile.
Is there a specific reason about mentioning Platform capabilities here? 😅 
The flow in Platform and MC is nearly same right now (configured through two parameters). I think usage of "However" would be misleading here.

2024-06-03 13:43 UTC, rebekah-lawrence commented on docs/modules/deploy-manage/pages/logging.adoc
> +NOTE: For a provided JSON logging template to be effective, you need to activate the `json-logging` profile.
I was looking at the Slack conversation you linked, where it says:

> Although Hazelcast Platform supports this out-of-the-box, MC requires some additional configuration.

It is just not logical to say that something is provided/supported OOTB when you still have to enable it. OOTB means no further config required, it just works.

Maybe just remove the first sentence from the existing version and start "To enable....."?

2024-06-03 14:06 UTC, emrberk commented on docs/modules/deploy-manage/pages/logging.adoc
> +NOTE: For a provided JSON logging template to be effective, you need to activate the `json-logging` profile.
It makes sense, I removed the first sentence 👍

2024-06-03 14:13 UTC, rebekah-lawrence approved these changes
Thanks for bearing with me ;-)

2024-06-03 16:28 UTC, emrberk commented
@rebekah-lawrence I guess the test failures are about Platform. Do we have an action item here, or can I merge this one?

2024-06-04 07:10 UTC, rebekah-lawrence commented
@emrberk Merging this should be fine. It will be on the SNAPSHOT branch; so pre-release information, which can still change. If any further changes are required after a solution to the test failures, we can handle it then.

2024-06-04 08:50 UTC, merged