5.5.0 release notes
hazelcast/management-center-docs pull request #336
Opened 2024-07-25 16:22 UTC by promanenko

2024-07-25 22:43 UTC, jgardiner68 requested changes
See https://github.com/hazelcast/management-center-docs/pull/337

2024-07-26 09:16 UTC, oliverhowell requested changes
Rewrote the data migration section, otherwise minor changes - though looks like your description is not displaying

2024-07-26 09:16 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +a custom run script, refer to the documentation for comprehensive instructions on migrating MC data. If the internal database is not upgraded, then MC will start with a new configuration.
```suggestion
IMPORTANT: If you are upgrading Management Center from a version earlier than 5.4.0, a data migration step is required as Management Center 5.5.0 uses H2 2.x as its internal database instead of H2 1.x (as used in previous releases). If you use the provided `hz-mc` or `mc-start` scripts to start Management Center, this data migration is handled automatically by the script. If you use a custom run script, refer to the documentation for comprehensive instructions on migrating Management Center data. If the internal database is not upgraded, then Management Center will start with a new configuration.
```
What is H2?
"refer to the documentation" which documentation? Is it ours? Can we link?

2024-07-26 09:16 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +{description}
```suggestion
These release notes list any new features, enhancements, and fixes that were made between version 5.4.1 and 5.5.0 of Hazelcast Management Center (MC).

{description}
```
Think you need above to make description display.
Bonus question: do we generally us MC as an acronym?

2024-07-26 09:16 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +* Added an ability to load OIDC configuration parameters from an OIDC configuration endpoint. [MC-2733]
```suggestion
* Added ability for WAN Replication reference of an IMaps. [MC-2729]
* Added ability to configure `consistency-check-strategy` during dynamic creation of a WAN publisher. [MC-243]
* Added ability to load OIDC configuration parameters from an OIDC configuration endpoint. [MC-2733]
```

2024-07-26 09:16 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +* Jet job Received Items count no longer increases the stream has been cancelled. [MC-2761]
```suggestion
* Jet job Received Items count no longer increases if the stream has been cancelled. [MC-2761]
```

2024-07-26 09:20 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +
```suggestion

NOTE: Hazelcast Management Center 5.5 requires Java 17 or later to run.

```

2024-07-26 10:18 UTC, promanenko commented on docs/modules/release-notes/pages/5-5-0.adoc
> +a custom run script, refer to the documentation for comprehensive instructions on migrating MC data. If the internal database is not upgraded, then MC will start with a new configuration.
H2 is a database as mentioned at the beginning. The documentation is ours https://docs.hazelcast.com/management-center/5.4/deploy-manage/h2-upgrade

2024-07-26 10:18 UTC, promanenko commented on docs/modules/release-notes/pages/5-5-0.adoc
> +{description}
yes, we use MC as an acronym

2024-07-26 10:20 UTC, promanenko commented on docs/modules/release-notes/pages/5-5-0.adoc
> +
we had this note in the previous release, there was no upgrade of the minimal required Java version in 5.5. Can we skip it?

2024-07-26 10:24 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +
Yeah, fine with me - that was my slack DM question tho

2024-07-26 10:32 UTC, oliverhowell requested changes

2024-07-26 10:32 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +{description}
I don't know why description isn't rendering in the page here so quick fix to replace variable with actual text:

```suggestion
These release notes list any new features, enhancements, and fixes that were made between version 5.4.1 and 5.5.0 of Hazelcast Management Center (MC).
```

2024-07-26 10:32 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +IMPORTANT: If you are upgrading Management Center from a version earlier than 5.4.0, a data migration step is required as Management Center 5.5.0 uses H2 2.x as its internal database instead of H2 1.
```suggestion
CAUTION: If you are upgrading Management Center from a version earlier than 5.4.0, a data migration step is required as Management Center 5.5.0 uses H2 2.x as its internal database instead of H2 1.x (as used in previous releases). If you use the provided `hz-mc` or `mc-start` scripts to start Management Center, this data migration is handled automatically by the script. If you use a custom run script, refer to the documentation for comprehensive instructions on migrating Management Center data. If the internal database is not upgraded, then Management Center will start with a new configuration.
```

2024-07-26 10:33 UTC, oliverhowell commented on docs/modules/release-notes/pages/5-5-0.adoc
> +IMPORTANT: If you are upgrading Management Center from a version earlier than 5.4.0, a data migration step is required as Management Center 5.5.0 uses H2 2.x as its internal database instead of H2 1.
Looking at other examples, and the coloring applied, we should switch to Caution - sorry for late switch

2024-07-26 11:58 UTC, oliverhowell approved these changes

2024-07-26 13:14 UTC, merged