Global antora file
hazelcast/management-center-docs pull request #386
Opened 2024-10-16 14:15 UTC by fantkolja

2024-10-29 15:46 UTC, JackPGreen requested changes

2024-10-29 15:46 UTC, JackPGreen commented on .github/workflows/validate.yml
> +        ref: main
What happens if someone opens a PR on a non-`main` branch in this repo?

2024-10-29 15:46 UTC, JackPGreen commented on package.json
> +    "@jcahills/antora-link-checker": "^1.0.1",
Turbo-nit - this is the same, just re-ordered?

2024-10-29 15:46 UTC, JackPGreen commented on check-links-playbook.yml
Should we also delete the definition from `package.json`?

2024-10-29 15:46 UTC, JackPGreen commented on load-check-links-playbook.js
_If_ the plan is to share this with other repos, can we centralise it?

2024-10-29 15:46 UTC, JackPGreen commented on load-check-links-playbook.js
Some summary documentation would help on what this does at a high-level.

2024-10-29 19:32 UTC, fantkolja commented on package.json
> +    "@jcahills/antora-link-checker": "^1.0.1",
Yes, just got reordered alphabetically , after I've launched `npm i`

2024-10-29 19:41 UTC, fantkolja commented on check-links-playbook.yml
The script [load-check-links-playbook.js](https://github.com/hazelcast/management-center-docs/pull/386/files#diff-ab850f5aa851d60af16ecfb679c1121f0977b511ba533ba919da38c7a640e1c7R44) creates that `check-links-playbook.yml` but on the fly.

But I also don't like that `check-links-local` references a non-existing file, so I will probably refactor this part in the further work...

2024-10-29 19:41 UTC, fantkolja commented on load-check-links-playbook.js
Will do both: centralizing and docs after we approve that the whole idea is worth implementing

2024-10-29 19:58 UTC, JackPGreen commented on .github/workflows/validate.yml
> +        ref: main
🤦

2024-11-14 12:26 UTC, JackPGreen approved these changes

2024-11-15 13:18 UTC, merged