MC-721: update metric-persistence.adoc
hazelcast/management-center-docs pull request #63
Opened 2021-07-13 14:30 UTC by zhmaeff

2021-07-13 14:59 UTC, erosb commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +It allows us to compress data to use less disk space.
suggestion:
> It allows you to compress data and spare disk space.

2021-07-13 14:59 UTC, erosb commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +That minute buckets are stored in-memory for 70 seconds.
nit: That -> These

2021-07-13 14:59 UTC, erosb commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +This directory can be changed using the `hazelcast.mc.home` property on the server where Management Center is running.
Suggestion:
The home directory can be changed using the `hazelcast.mc.home` system property.

2021-07-13 14:59 UTC, erosb commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +This message indicates that for the last minute Management Center tried to persist more metrics than underlying persistent storage or disk throughput.
Suggestion:
> This message indicates that for the last minute, Management Center could not persist all collected metrics due to disk write throughput limitations.

2021-07-13 14:59 UTC, erosb commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +If this message keeps showing up in log, please consider decreasing count of collected metrics on cluster side.
Suggestion:
> ... please consider reducing the collected metrics, for example by changing the `statistics-enabled` configuration attributes of distributed data structures to `false`.

2021-07-13 15:37 UTC, zhmaeff commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +This message indicates that for the last minute Management Center tried to persist more metrics than underlying persistent storage or disk throughput.
Actually, Management Center could persist all collected metrics but it was slower than expected and it may cause JVM heap pollution, because metric minute buckets number growing faster than we dump them to disk.

2021-07-13 15:40 UTC, zhmaeff commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +This message indicates that for the last minute Management Center tried to persist more metrics than underlying persistent storage or disk throughput.
And that is only when we receive warning log message multiple times in a row.

2021-07-14 07:01 UTC, erosb approved these changes
Approving, but please don't merge it yet.

2021-07-14 10:44 UTC, JakeSCahill requested changes
Thanks 😄 The content is good, I just added some suggestions to bring the focus back to what the user needs to know to accomplish a goal (change the persisted metrics TTL/directory).

2021-07-14 10:44 UTC, JakeSCahill commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +Management Center metrics persistence accumulating collected metrics into minute buckets (data points of same time series for 1 minute).
This sentence is quite confusing.

Consider something like this (to replace the new changes until 'You may see the following warning messages in the Management Center log'):

To save memory and improve performance, Management Center groups metrics into one-minute buckets before compressing them and saving them to disk. These persisted metrics are stored in the `<User‘s Home Directory>/hazelcast-mc/metrics`
folder for one day.

If you want to store persisted metrics in a different folder, set the `hazelcast.mc.home` property on the server where Management Center is running.

If you want to store persisted metrics for a different amount of time, use the xref:configuring.adoc#disk-usage-config[Time-to-Live] setting.

To collect metrics,  Management Center starts a metrics-persistence thread that checks for new one-minute buckets every 10 seconds.

To allow for late metrics due to poor connection or other retryable errors, the metrics-peristence thread waits until one-minute buckets are 70 seconds old. This way, one-minute buckets have a 10 second threshold in which late data may be saved to disk.

For example:

. MC received first chunk of metrics at 9:00:00 AM.
. A one-minute bucket is created for each metric type (CPU, heap, etc) in memory and each bucket's timestamp is set to 9:00:00 AM. At this point nothing is saved to disk.
. The next chunk of metrics is received at 9:00:03 AM. No new minute buckets created, only the new metrics are added to the existing one-minute bucket.
. The first metrics-persistence thread starts at 9:00:10 AM. The thread didn’t find any minute buckets that are 70 seconds old. Still nothing is stored on disk.
. At 9:01:10 AM, the metrics-persistence thread stores the compressed one-minute buckets on disk.

2021-07-14 10:44 UTC, JakeSCahill commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +See the xref:imdg:management:metrics.adoc[Metrics section] of the Hazelcast documentation
Would you like us to backport these changes to other versions of MC?

2021-07-15 08:58 UTC, zhmaeff commented on docs/modules/ROOT/pages/metric-persistence.adoc
> +See the xref:imdg:management:metrics.adoc[Metrics section] of the Hazelcast documentation
>Would you like us to backport these changes to other versions of MC?
No, this documentation updates is relevant only for 5.0.

2021-07-15 09:16 UTC, JakeSCahill approved these changes
LGTM, thanks 😄

2021-07-15 09:18 UTC, merged